"""Generate the Shopify Custom Pixel that feeds GTM.

Shopify's checkout no longer runs theme scripts, so tracking that must cover
checkout and the thank-you page goes through a Custom Pixel (Settings >
Customer events). The pixel runs in a sandboxed iframe: it loads GTM there,
subscribes to Shopify's standard events and pushes GA4-schema ecommerce
events to the dataLayer that the generated GTM container listens for.

Shopify has no Admin API for custom pixels, so this code is pasted by hand.
"""

from __future__ import annotations

import json
from typing import Any

_ITEM_ID_EXPR = {
    "variant_id": "String(variant.id)",
    "product_id": "String(variant.product && variant.product.id)",
    "sku": "String(variant.sku || variant.id)",
    "shopify_feed": "'shopify_' + FEED_COUNTRY + '_' + (variant.product && variant.product.id) + '_' + variant.id",
}

PIXEL_TEMPLATE = r"""// Generated by tracking-agent for __STORE_NAME__.
// Paste into Shopify Admin > Settings > Customer events > Add custom pixel.
const GTM_ID = __GTM_ID__;
const DEFAULT_CURRENCY = __CURRENCY__;
const FEED_COUNTRY = __FEED_COUNTRY__;

window.dataLayer = window.dataLayer || [];
function gtag() { window.dataLayer.push(arguments); }

// ---- Consent Mode v2, driven by Shopify's customer privacy state ----------
function consentState(privacy) {
  const granted = (allowed) => (allowed ? 'granted' : 'denied');
  return {
    ad_storage: granted(privacy.marketingAllowed),
    ad_user_data: granted(privacy.marketingAllowed),
    ad_personalization: granted(privacy.marketingAllowed),
    analytics_storage: granted(privacy.analyticsProcessingAllowed),
    functionality_storage: granted(privacy.preferencesProcessingAllowed),
    personalization_storage: granted(privacy.preferencesProcessingAllowed),
    security_storage: 'granted',
  };
}
const initialPrivacy = (typeof init !== 'undefined' && init.customerPrivacy) || {};
gtag('consent', 'default', { ...consentState(initialPrivacy), wait_for_update: 500 });
if (typeof customerPrivacy !== 'undefined' && customerPrivacy.subscribe) {
  customerPrivacy.subscribe('visitorConsentCollected', (event) => {
    gtag('consent', 'update', consentState(event.customerPrivacy));
  });
}

// ---- Load GTM inside the pixel sandbox ------------------------------------
(function (w, d, s, l, i) {
  w[l] = w[l] || [];
  w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
  const f = d.getElementsByTagName(s)[0];
  const j = d.createElement(s);
  const dl = l !== 'dataLayer' ? '&l=' + l : '';
  j.async = true;
  j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
  f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', GTM_ID);

// ---- Helpers --------------------------------------------------------------
function itemId(variant) {
  return __ITEM_ID_EXPR__;
}

function variantToItem(variant, quantity, index) {
  if (!variant) return null;
  const product = variant.product || {};
  return {
    item_id: itemId(variant),
    item_name: product.title || variant.title,
    item_variant: variant.title,
    item_brand: product.vendor,
    item_category: product.type,
    price: Number(variant.price && variant.price.amount) || 0,
    quantity: quantity || 1,
    index: index,
  };
}

function checkoutItems(checkout) {
  return (checkout.lineItems || [])
    .map((line, i) => variantToItem(line.variant, line.quantity, i))
    .filter(Boolean);
}

function cartItems(cart) {
  return ((cart && cart.lines) || [])
    .map((line, i) => variantToItem(line.merchandise, line.quantity, i))
    .filter(Boolean);
}

let pageContext = {};

function push(eventName, shopifyEvent, ecommerce, extra) {
  const ctx = (shopifyEvent.context && shopifyEvent.context.document) || {};
  if (ctx.location) {
    pageContext = {
      page_location: ctx.location.href,
      page_referrer: ctx.referrer,
      page_title: ctx.title,
    };
  }
  const items = (ecommerce && ecommerce.items) || [];
  window.dataLayer.push({ ecommerce: null }); // clear previous ecommerce object
  window.dataLayer.push({
    event: eventName,
    event_id: shopifyEvent.id,
    ...pageContext,
    content_ids: items.map((item) => item.item_id),
    num_items: items.reduce((sum, item) => sum + (item.quantity || 0), 0),
    ...(extra || {}),
    ecommerce: ecommerce || undefined,
  });
}

function checkoutEcommerce(checkout) {
  return {
    currency: checkout.currencyCode || DEFAULT_CURRENCY,
    value: Number(checkout.totalPrice && checkout.totalPrice.amount) || 0,
    coupon: (checkout.discountApplications || []).map((d) => d.title).join(',') || undefined,
    items: checkoutItems(checkout),
  };
}

function checkoutUserData(checkout) {
  const userData = {};
  if (checkout.email) userData.email = checkout.email.trim().toLowerCase();
  const phone = checkout.phone || (checkout.billingAddress && checkout.billingAddress.phone);
  if (phone) userData.phone = phone;
  return { user_data: userData };
}

// ---- Shopify standard events -> GA4-schema dataLayer events ---------------
analytics.subscribe('page_viewed', (event) => {
  push('page_view', event);
});

analytics.subscribe('collection_viewed', (event) => {
  const collection = event.data.collection || {};
  const items = (collection.productVariants || [])
    .map((variant, i) => variantToItem(variant, 1, i))
    .filter(Boolean);
  push('view_item_list', event, {
    item_list_id: collection.id,
    item_list_name: collection.title,
    currency: DEFAULT_CURRENCY,
    items,
  });
});

analytics.subscribe('search_submitted', (event) => {
  const result = event.data.searchResult || {};
  push('search', event, null, { search_term: result.query });
});

analytics.subscribe('product_viewed', (event) => {
  const variant = event.data.productVariant;
  const item = variantToItem(variant, 1, 0);
  push('view_item', event, {
    currency: (variant && variant.price && variant.price.currencyCode) || DEFAULT_CURRENCY,
    value: item ? item.price : 0,
    items: item ? [item] : [],
  });
});

analytics.subscribe('product_added_to_cart', (event) => {
  const line = event.data.cartLine;
  if (!line) return;
  const item = variantToItem(line.merchandise, line.quantity, 0);
  const total = line.cost && line.cost.totalAmount;
  push('add_to_cart', event, {
    currency: (total && total.currencyCode) || DEFAULT_CURRENCY,
    value: Number(total && total.amount) || (item ? item.price * item.quantity : 0),
    items: item ? [item] : [],
  });
});

analytics.subscribe('cart_viewed', (event) => {
  const cart = event.data.cart;
  const total = cart && cart.cost && cart.cost.totalAmount;
  push('view_cart', event, {
    currency: (total && total.currencyCode) || DEFAULT_CURRENCY,
    value: Number(total && total.amount) || 0,
    items: cartItems(cart),
  });
});

analytics.subscribe('checkout_started', (event) => {
  const checkout = event.data.checkout;
  push('begin_checkout', event, checkoutEcommerce(checkout), checkoutUserData(checkout));
});

analytics.subscribe('checkout_shipping_info_submitted', (event) => {
  const checkout = event.data.checkout;
  const ecommerce = checkoutEcommerce(checkout);
  ecommerce.shipping_tier = checkout.delivery && checkout.delivery.selectedDeliveryOptions
    ? checkout.delivery.selectedDeliveryOptions.map((o) => o.title).join(',')
    : undefined;
  push('add_shipping_info', event, ecommerce, checkoutUserData(checkout));
});

analytics.subscribe('payment_info_submitted', (event) => {
  const checkout = event.data.checkout;
  push('add_payment_info', event, checkoutEcommerce(checkout), checkoutUserData(checkout));
});

analytics.subscribe('checkout_completed', (event) => {
  const checkout = event.data.checkout;
  const ecommerce = checkoutEcommerce(checkout);
  ecommerce.transaction_id = String((checkout.order && checkout.order.id) || checkout.token);
  ecommerce.tax = Number(checkout.totalTax && checkout.totalTax.amount) || 0;
  ecommerce.shipping = Number(checkout.shippingLine && checkout.shippingLine.price && checkout.shippingLine.price.amount) || 0;
  push('purchase', event, ecommerce, checkoutUserData(checkout));
});
"""


def build_pixel(config: dict[str, Any]) -> str:
    store = config["store"]
    source = store.get("item_id_source", "variant_id")
    if source not in _ITEM_ID_EXPR:
        raise ValueError(f"Unsupported item_id_source '{source}'. Use one of {list(_ITEM_ID_EXPR)}.")
    replacements = {
        "__STORE_NAME__": store.get("name") or "your store",
        "__GTM_ID__": json.dumps(config["gtm"]["container_public_id"]),
        "__CURRENCY__": json.dumps(store.get("currency", "USD")),
        "__FEED_COUNTRY__": json.dumps(store.get("feed_country", "US")),
        "__ITEM_ID_EXPR__": _ITEM_ID_EXPR[source],
    }
    code = PIXEL_TEMPLATE
    for placeholder, value in replacements.items():
        code = code.replace(placeholder, value)
    return code
